# ml-service/src/data_generator.py
import random
import pandas as pd
from datetime import datetime

# ---------------------------------------------------------------------------
# Real-world log patterns — hard-coded, non-template strings that reflect
# actual production log output from common systems (Linux kernel, PostgreSQL,
# Redis, nginx, JVM, Go runtime, Node.js, Kubernetes, Kafka, etc.).
# These complement the template-based generator to give the ML model
# exposure to realistic vocabulary and formatting.
# ---------------------------------------------------------------------------

REAL_WORLD_PATTERNS = {
    "critical": [
        # OOM / memory exhaustion
        "OOM killer invoked, killed process nginx pid=12453",
        "OOM killer invoked, killed process postgresql pid=7823",
        "OOM killer invoked, killed process redis-server pid=3421",
        "OOM killer invoked, killed process node pid=5623 score=897",
        "kernel: Out of memory: Kill process 8234 (java) score 987 or sacrifice child",
        "kernel: BUG: unable to handle page fault for address: 0x0000000000000010",
        "kernel: BUG: unable to handle page fault for address: 0xffff888000000000",
        "SIGKILL sent to pid 8823, reason: cgroup memory limit exceeded limit=512MB used=514MB",
        "SIGKILL sent to pid 2341, reason: cgroup memory limit exceeded limit=2GB used=2.1GB",
        "Container oom-killed: postgres container exceeded memory limit 4Gi",
        "java.lang.OutOfMemoryError: Java heap space",
        "java.lang.OutOfMemoryError: GC overhead limit exceeded",
        "fatal error: runtime: out of memory (requested 4294967296 bytes)",
        "malloc: cannot allocate region: Cannot allocate memory",
        "Swap space exhausted: unable to allocate memory for critical process",
        "RSS memory limit exceeded: killing container limit=8192MB rss=8521MB",
        "MemAvailable: 0 kB, system is completely out of memory",
        # Kernel / system panics
        "kernel panic - not syncing: Fatal exception in interrupt",
        "kernel panic - not syncing: VFS: Unable to mount root fs on unknown-block",
        "Segmentation fault (core dumped) process=api-server pid=4523",
        "Segmentation fault (core dumped) process=worker pid=7821",
        "panic: runtime error: index out of range [5] with length 3 goroutine 1",
        "panic: runtime error: invalid memory address or nil pointer dereference",
        "panic: interface conversion: interface {} is nil, not *models.User",
        "SIGSEGV received in thread 0x7f4c2b000700, aborting",
        "fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr=0x0",
        "double free or corruption (out): 0x00007f0d9c000b20",
        # Database total failures
        "FATAL: max_connections exceeded, refusing new connections",
        "FATAL: the database system is in recovery mode",
        "FATAL: terminating connection due to administrator command",
        "PANIC: could not write to file pg_wal/00000001000000010000007A: No space left",
        "FATAL: database files are incompatible with server (db version: 140001, server: 150003)",
        "FATAL: WAL file is too large, streaming replication halted",
        "etcd cluster is unavailable, lost quorum (1/3 members reachable)",
        "etcd: failed to obtain lease, cluster may be unhealthy",
        "SQLSTATE[HY000]: Table './prod_db/orders' is marked as crashed and should be repaired",
        "InnoDB: Assertion failure: btr0btr.cc line 2785",
        # Storage failures
        "zfs pool 'data' status: DEGRADED - one or more devices has been removed",
        "zfs pool 'data' status: FAULTED - the pool metadata is corrupted",
        "md/raid1:md0: Disk failure on sdb1, disabling device",
        "EXT4-fs error (device sda1): ext4_find_entry: reading directory lblock 0",
        "Buffer I/O error on device sda, logical block 4096",
        "SCSI error: return code = 0x08000002, host_status=0x01 driver_status=0x00",
        "device-mapper: multipath: Failing path sdb",
        "No space left on device: /dev/sda1 (100% full)",
        # Service complete outages
        "nginx: [emerg] bind() to 0.0.0.0:443 failed (98: Address already in use)",
        "nginx: [emerg] cannot load certificate /etc/ssl/certs/server.crt: BIO_new_file() failed",
        "systemd[1]: postgresql.service: Main process exited, code=killed, status=9/KILL",
        "systemd[1]: redis.service: Failed with result exit-code",
        "Failed to connect to the hypervisor: Failed to initialize KVM",
        "Kubernetes node NotReady: container runtime is not responding",
        "pod/api-server CrashLoopBackOff: back-off 5m0s restarting failed container",
        # Security breaches
        "sshd[3421]: Received disconnect from 198.51.100.42: Too many authentication failures",
        "pam_unix(sshd:auth): authentication failure; user=root rhost=192.0.2.1",
        "CRITICAL: Possible rootkit detected - /proc/net/tcp modified",
        "auditd: SELinux is enforcing, denying access to /etc/shadow for process 3823",
        "iptables: DROP IN=eth0 SRC=203.0.113.0 DPT=22 possible port scan",
        "CRITICAL: JWT secret key exposed in environment variable REACT_APP_SECRET",
        "SQL injection attempt detected in request body: DROP TABLE users",
        "Privilege escalation attempt detected: user www-data tried to exec sudo",
        # Network infrastructure
        "BGP session to 192.0.2.1 went down: hold timer expired",
        "OSPF neighbor 10.0.0.2 went down: dead interval expired",
        "Interface eth0 link is down: carrier lost",
        "Spanning tree topology change detected on port GigabitEthernet0/1",
        "HSRP: Active router changed from 10.0.0.1 to 10.0.0.2 (network instability)",
        # Container / orchestration
        "node.kubernetes.io/not-ready taint added to node worker-3",
        "Eviction manager: evicting pod high-memory-pod due to memory pressure",
        "Docker daemon is not responding, container runtime unavailable",
        "ContainerCannotRun: cannot start container: error gathering device information",
        # Data corruption
        "ERROR: could not read from file: read on block 9745 of relation base/16384/pg_toast_2619 failed: Input/output error",
        "Data integrity check failed: expected checksum=0xdeadbeef got=0xcafebabe",
        "Redis: MISCONF Redis is configured to save RDB snapshots, but is currently not able to persist on disk",
        "Cassandra: Corrupt sstable detected in table keyspace.users, dropping data",
        "MongoDB: WiredTiger error (-31803) WT_PANIC: WiredTiger library panic",
        # Application-level critical
        "FATAL: Circuit breaker OPEN for service payment-gateway after 10 consecutive failures",
        "CRITICAL: Dead letter queue exhausted, messages being dropped",
        "FATAL: License key expired, application will terminate in 0 hours",
        "CRITICAL: Consensus protocol failed, split-brain condition detected",
        "FATAL: Unable to acquire distributed lock after 30000ms, aborting transaction",
        # Additional
        "CRITICAL: SSL certificate for api.example.com expired 2 days ago, all HTTPS failing",
        "CRITICAL: Backup verification failed - last 5 backups are corrupt",
        "CRITICAL: Primary node unreachable, automatic failover initiated to replica-2",
        "FATAL: Process table full, no more processes can be created (limit=65535)",
        "CRITICAL: All connection pool threads exhausted, queued requests: 1247",
        "FATAL: glibc detected heap corruption: double linked list corrupted",
        "CRITICAL: Firewall ruleset failed to load, all traffic permitted (fail-open)",
        "FATAL: Master encryption key unavailable, cannot decrypt sensitive data",
        "CRITICAL: Split brain detected: both nodes believe they are primary",
        "FATAL: Write-ahead log full, database is read-only until space freed",
        "CRITICAL: Health check endpoint unresponsive for 5 consecutive checks",
        "FATAL: Thread pool saturated: 500/500 threads active, rejecting work",
        # Cluster / consensus
        "CRITICAL: Raft leader election failed, no leader elected after 30s",
        "CRITICAL: ZooKeeper session expired, distributed coordination unavailable",
        "CRITICAL: Consul health check failed for all nodes in datacenter dc1",
        "FATAL: HAProxy backend servers all down: no healthy server for pool api",
        "CRITICAL: Kubernetes API server unreachable from all worker nodes",
        "FATAL: etcd compaction failed, disk space may be exhausted",
        "CRITICAL: Redis Sentinel failover failed, no replica promoted",
        "FATAL: CockroachDB node lost connection to 3/5 cluster members",
        # Application crashes
        "FATAL: segmentation violation (SIGSEGV) at address 0x0 in main thread",
        "FATAL: stack overflow detected in request handler goroutine",
        "FATAL: process received SIGABRT, core dumped to /var/core/api.core",
        "FATAL: pthread_create failed: Cannot allocate memory (errno=12)",
        "FATAL: execve failed: Argument list too long",
        "FATAL: fork failed: Resource temporarily unavailable (errno=11)",
        "CRITICAL: recursive mutex lock detected, aborting to prevent deadlock",
        "FATAL: assertion failed: ptr != NULL at src/allocator.c:234",
        # Storage / IO
        "CRITICAL: RAID controller battery backup failed, write cache disabled",
        "FATAL: filesystem /data entered read-only mode due to journal errors",
        "CRITICAL: NFS mount point /mnt/shared is stale, I/O operations hanging",
        "FATAL: LVM logical volume /dev/vg0/data has failed, data inaccessible",
        "CRITICAL: S3 bucket policy prevents writes, data loss may occur",
        "FATAL: Ceph pool degraded: 47 PGs in inconsistent state",
        "CRITICAL: iSCSI target lost connection, volumes unmounted unexpectedly",
        "FATAL: bcache dirty data loss detected after unclean shutdown",
        # Network catastrophic
        "CRITICAL: DNS resolution completely failed: /etc/resolv.conf empty",
        "FATAL: All upstream load balancer backends unreachable (health: 0/8)",
        "CRITICAL: Certificate Authority root cert expired, all TLS failing",
        "FATAL: iptables rules flushed by accident, firewall completely open",
        "CRITICAL: BGP route table full: 900000/1000000 routes, dropping peers",
        "FATAL: MTU mismatch caused network partition between AZ-1 and AZ-2",
        # JVM critical
        "FATAL: JVM crash at C [libc.so.6+0x7b10a] malloc+0xa",
        "CRITICAL: Java heap exhausted during Full GC, VM will terminate",
        "FATAL: JVM internal error: ShouldNotReachHere() in nativeInst_x86.cpp",
        "CRITICAL: ClassLoader deadlock detected: failing thread group",
        # Python/Ruby/PHP critical
        "FATAL: Python interpreter ran out of memory during garbage collection",
        "CRITICAL: Ruby MRI: signal received in non-main thread, aborting",
        "FATAL: PHP-FPM master process died unexpectedly (signal 11)",
        "CRITICAL: Gunicorn arbiter error: worker timeout, sending SIGKILL",
        # Secrets / certificates
        "CRITICAL: Private key for signing JWTs not found at /run/secrets/jwt_key",
        "FATAL: HSM device not responding, cryptographic operations halted",
        "CRITICAL: KMS key rotation failed, encryption keys may be compromised",
        "FATAL: Vault seal detected, secrets engine unavailable",
        # Additional
        "CRITICAL: Prometheus scrape target down for 15 minutes, alerting blind",
        "FATAL: Fluentd log shipping buffer full: 10GB, dropping logs",
        "CRITICAL: Terraform state lock held by pid 23456 for >60 minutes",
        "FATAL: Ansible playbook left cluster in partially-upgraded state",
        "CRITICAL: Docker image layer corrupted in registry, deployments failing",
        "FATAL: Helm release rollback failed: previous revision also broken",
        "CRITICAL: CI/CD pipeline stuck: no runners available for 45 minutes",
        "FATAL: Database schema migration failed at step 42, rollback aborted",
        "CRITICAL: Message broker quorum lost: 2/5 brokers unreachable",
        "FATAL: Backup job failed for 7 consecutive days, no valid backup exists",
        "CRITICAL: Rate limiter data store unreachable, falling back to no-limit",
        "FATAL: Grafana data source PostgreSQL connection lost, dashboards down",
        "CRITICAL: Alertmanager unable to send alerts: SMTP auth failure",
        "FATAL: Jaeger tracing backend disk full, traces being dropped",
        "CRITICAL: OpenTelemetry collector crashed, observability gap in progress",
        "FATAL: Service mesh proxy Envoy crash-looping on all nodes",
        "CRITICAL: Feature flag service unavailable, all flags defaulting to off",
        "FATAL: Config management server unreachable, stale config in use",
        "CRITICAL: Auto-scaler failed to provision nodes: quota exceeded",
        "FATAL: Load shedding activated: rejecting 100% of non-critical traffic",
        "CRITICAL: Database primary server unreachable, read-only replica elected as new primary",
        "FATAL: Service account credentials revoked, all API calls failing with 401",
        "CRITICAL: Antivirus detected malware in uploaded file, system quarantine activated",
        "FATAL: Distributed transaction coordinator down, all 2PC transactions blocked",
        "CRITICAL: Message queue storage full, all producers blocked",
        "FATAL: Replication factor 1 (below minimum 2), data durability compromised",
        "CRITICAL: SLA breach imminent: 99.5% uptime at risk, 23 minutes remaining in window",
        "FATAL: Core router failure, all inter-datacenter traffic severed",
        "CRITICAL: Database certificate expired, all encrypted connections rejected",
        "FATAL: Production database accidentally dropped — point-in-time recovery initiated",
        "CRITICAL: All backup sites unreachable during primary datacenter outage",
        "FATAL: Memory-mapped file corrupted: /var/db/primary.mmap size=0 expected=4096MB",
        "CRITICAL: watchdog timer expired, system will reboot in 30 seconds",
        "FATAL: Hardware fault detected on storage controller, array entering degraded mode",
        "CRITICAL: Clock drift of 4.7 seconds detected, distributed consensus at risk",
        "FATAL: BIOS hardware watchdog triggered unexpected reboot of node worker-2",
        "CRITICAL: All replicas reporting inconsistent data — split-brain recovery required",
        "FATAL: SSH host key mismatch on prod-server-1, possible MITM attack",
        "CRITICAL: Root filesystem 100% full on api-server-3, process crashes imminent",
        "FATAL: Shared secret rotation failed — old and new keys both invalid",
        "CRITICAL: Circuit breaker permanently OPEN for all downstream services",
        "FATAL: Emergency stop triggered by ops team — all write operations halted",
        "CRITICAL: License validation server unreachable — grace period expires in 1 hour",
        "FATAL: Distributed lock service down — race conditions across all workers possible",
        "CRITICAL: Batch job corrupted 45000 records — rollback transaction initiated",
        "FATAL: Config push deployed broken certificate — HTTPS failing cluster-wide",
        "CRITICAL: Health check loop detected — service constantly restart-crashing",
        "FATAL: Reserved IP address reassigned — split cluster now sharing same IP",
        "CRITICAL: Emergency backup restore in progress — database read-only for ~90 minutes",
        "FATAL: Object storage quota exceeded — all uploads failing with 507",
        "CRITICAL: Token signing service down — all new logins failing with 500",
        "FATAL: All CDN PoPs unreachable — traffic falling back to origin at 100x load",
        "CRITICAL: Runtime version mismatch — node v14 binary running on v20 cluster",
        "FATAL: Thread deadlock detected in payment processor — all charges stalled",
        "CRITICAL: Pod security policy violation — admission webhook rejecting all deploys",
        "FATAL: Write-ahead log corruption detected at offset 0x7B000000",
        "CRITICAL: Hot partition detected — single shard receiving 100% of write traffic",
        "FATAL: Infinite retry storm — 50000 rpc calls per second hitting auth service",
        "CRITICAL: API gateway config invalid — all routes returning 502",
        "FATAL: Webhook secret mismatch — all incoming webhooks rejected",
        "CRITICAL: Master key shards insufficient for decryption (need 3/5, have 2)",
        "FATAL: Power supply failure detected — UPS on battery, runtime ~12 minutes",
        "CRITICAL: Network switch firmware panic — all traffic on VLAN 100 dropped",
        "FATAL: Kubernetes API admission webhook unavailable — all pod creation blocked",
        "CRITICAL: Primary etcd endpoint cert expired — control plane operations failing",
        "FATAL: Database encryption key not found in HSM — decryption impossible",
        "CRITICAL: Network time protocol desynchronised — distributed locks unreliable",
    ],
    "error": [
        # Connection errors
        "ECONNREFUSED 127.0.0.1:5432 connect ECONNREFUSED",
        "ECONNREFUSED 127.0.0.1:6379 connect ECONNREFUSED",
        "ECONNREFUSED ::1:27017 connect ECONNREFUSED",
        "ETIMEDOUT 10.0.0.5:9200 - connection timed out after 30000ms",
        "EHOSTUNREACH 192.168.1.100:8080 - no route to host",
        "dial tcp 10.0.0.3:5432: connect: connection refused",
        "dial tcp 10.0.0.5:6379: connect: connection timed out",
        "Error: connect ECONNRESET 10.0.0.1:443",
        # Database errors
        "SQLSTATE[HY000]: General error: 2006 MySQL server has gone away",
        "SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry for key PRIMARY",
        "SQLSTATE[22001]: String data right truncation: 1406 Data too long for column email",
        "ERROR: deadlock detected DETAIL: Process 23456 waits for ShareLock on transaction 7823",
        "ERROR: canceling statement due to conflict with recovery",
        "ERROR: relation 'orders_2024' does not exist",
        "ERROR: value too long for type character varying(255)",
        "ERROR: permission denied for table users",
        "ERROR: duplicate key value violates unique constraint users_email_key",
        "ERROR: foreign key violation: key (user_id)=(99999) is not present in table users",
        "ERROR: column orders.customer_id does not exist",
        "PG::UndefinedTable: ERROR: relation accounts does not exist",
        "ActiveRecord::RecordNotUnique: PG::UniqueViolation: ERROR",
        # HTTP / API errors
        "429 Too Many Requests upstream exhausted rate limit",
        "502 Bad Gateway: upstream connect error or disconnect/reset before headers",
        "503 Service Unavailable: no healthy upstream",
        "504 Gateway Timeout: upstream request timeout",
        "curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to api.stripe.com:443",
        "HTTP 401 Unauthorized: Bearer token expired or invalid",
        "HTTP 403 Forbidden: IP 203.0.113.42 not in allowed CIDR list",
        "Error: Request failed with status code 500 (POST /api/v2/charge)",
        # SSL/TLS errors
        "SSL_ERROR_HANDSHAKE_FAILURE_ALERT received from peer",
        "SSL: error:1408F10B:SSL routines:ssl3_get_record:wrong version number",
        "SSL: error:04091068:rsa routines:int_rsa_verify:bad signature",
        "certificate has expired or is not yet valid (notAfter=Jan 1 00:00:00 2024 GMT)",
        "x509: certificate signed by unknown authority",
        "x509: certificate is valid for api.internal, not api.production.example.com",
        "TLS handshake error from 10.0.0.1:52341: remote error: tls: bad certificate",
        # Application exceptions
        "java.lang.NullPointerException at com.app.UserService.getUser(UserService.java:142)",
        "java.lang.NullPointerException at com.app.PaymentProcessor.charge(PaymentProcessor.java:89)",
        "java.lang.ClassCastException: String cannot be cast to Integer at OrderService.java:221",
        "java.sql.SQLTimeoutException: Timeout after 30000ms waiting for a connection",
        "org.springframework.dao.DataAccessException: Could not extract ResultSet",
        "SyntaxError: Unexpected token < in JSON at position 0",
        "TypeError: Cannot read properties of undefined (reading 'id')",
        "TypeError: Cannot read properties of null (reading 'email')",
        "ReferenceError: user is not defined at /app/routes/profile.js:45",
        "UnhandledPromiseRejectionWarning: Error: getaddrinfo ENOTFOUND db.internal",
        "Error: ENOENT: no such file or directory, open '/var/app/config.json'",
        "Error: EACCES: permission denied, open '/etc/ssl/private/server.key'",
        "ValueError: invalid literal for int() with base 10: 'undefined'",
        "AttributeError: 'NoneType' object has no attribute 'split'",
        "KeyError: 'user_id' in dictionary at handlers/auth.py:78",
        "panic: assignment to entry in nil map goroutine 12 [running]",
        "runtime error: invalid memory address or nil pointer dereference [recovered]",
        # File system errors
        "open /var/run/app.pid: permission denied",
        "rename /tmp/upload.7f3a2b /var/uploads/file.pdf: no such file or directory",
        "write /var/log/app.log: disk quota exceeded",
        "Error: EMFILE: too many open files, open '/var/uploads/doc.pdf'",
        "IOError: [Errno 5] Input/output error: '/mnt/data/records.db'",
        # Message queue / broker errors
        "Kafka consumer group my-group lost partition assignment for topic events",
        "RabbitMQ: channel error; reason: {amqp_error,precondition_failed,message too large}",
        "Redis WRONGTYPE Operation against a key holding wrong kind of value",
        "Celery: Task app.tasks.send_email[abc-123] raised exception: SMTPException",
        "SQS: Failed to delete message after 3 attempts, message will become visible again",
        # Auth errors
        "LDAP error: Invalid credentials (49) for user uid=john,dc=corp,dc=com",
        "OAuth2 error: invalid_grant - refresh token expired or revoked",
        "JWT error: JsonWebTokenError: invalid signature",
        "Keycloak: Session not found or expired for token abc123def",
        "bcrypt compare failed: Invalid hash prefix",
        # Additional
        "gRPC error: code=Unavailable desc=transport is closing",
        "gRPC error: code=DeadlineExceeded desc=context deadline exceeded",
        "Elasticsearch: [search_phase_execution_exception] shard failures: no active shards",
        "Failed to decode response body: unexpected EOF",
        "Error acquiring mutex: context deadline exceeded after 5s",
        "circuit breaker tripped for service inventory-api (5 failures in 60s)",
        "Failed to process message id=msg_abc123: schema validation failed",
        "PaymentError: Card declined (code: insufficient_funds) for charge ch_abc123",
        "S3 error: NoSuchBucket: The specified bucket does not exist bucket=prod-uploads",
        "S3 error: AccessDenied: s3:GetObject on arn:aws:s3:::prod-backups/dump.sql",
        "WebSocket upgrade failed: 403 Forbidden from upstream",
        "Request body too large: limit=10MB received=15.3MB",
        "Session store error: ENOTFOUND redis.cluster.internal",
        "Failed to serialize response: circular reference detected in object",
        "Unexpected end of JSON input while parsing response from payment service",
        # Additional error patterns
        "Error: getaddrinfo ENOTFOUND postgres.cluster.internal",
        "Error: getaddrinfo ENOTFOUND redis.cluster.internal",
        "Error: self-signed certificate in certificate chain",
        "Error: write EPIPE broken pipe to downstream client",
        "Error: read ECONNRESET socket hang up",
        "Error: socket hang up after 30000ms idle",
        "ENOSPC: no space left on device, write /var/log/app.log",
        "EMFILE: too many open files, open limit=1024 current=1024",
        "ENFILE: file table overflow",
        "ENOMEM: cannot allocate memory for new request handler",
        "MaxListenersExceededWarning: Possible EventEmitter memory leak",
        "UnhandledPromiseRejectionWarning: Error: connect ECONNREFUSED 10.0.0.5:5432",
        "UnhandledPromiseRejectionWarning: SequelizeConnectionError: connect ETIMEDOUT",
        "GraphQL error: Cannot query field userProfile on type Query",
        "GraphQL error: Expected a value of type UserRole but received: SUPERUSER",
        "Protobuf decode error: unexpected wire type (got 5, want 0) for field user_id",
        "gRPC error: code=ResourceExhausted desc=quota exceeded for user",
        "gRPC error: code=PermissionDenied desc=user does not have permission",
        "WebSocket error: 1006 Connection closed abnormally (without close frame)",
        "WebSocket error: 1011 Internal server error in frame handler",
        "SSE connection error: write error after client disconnect",
        "Redis error: WRONGTYPE Operation against key holding wrong kind",
        "Redis error: ERR max number of clients reached",
        "Redis error: READONLY You cannot write against a read only replica",
        "Redis error: CLUSTERDOWN The cluster is down. Use CLUSTER INFO for more information",
        "Kafka producer error: Message was too large for server, topic=orders",
        "Kafka consumer error: Revocation of partition assignment timed out",
        "Kafka error: Broker 2 is not available (cluster might be starting)",
        "RabbitMQ channel error: NOT_FOUND exchange orders.dead.letter",
        "AMQP connection error 320: CONNECTION_FORCED - broker forced connection closure",
        "Elasticsearch error: search_phase_execution_exception all shards failed",
        "Elasticsearch error: cluster_block_exception index is read-only (disk full)",
        "MongoDB error: MongoNetworkError: failed to connect to server on first connect",
        "MongoDB error: MongoWriteConcernError: waiting for replication timed out",
        "Cassandra error: ReadTimeoutException: operation timed out (received=1, required=2)",
        "Cassandra error: WriteTimeoutException: operation timed out (received=0, required=2)",
        "DynamoDB error: ProvisionedThroughputExceededException table=users",
        "DynamoDB error: ConditionalCheckFailedException item already exists",
        "Firestore error: DEADLINE_EXCEEDED reading document users/abc123",
        "BigQuery error: quotaExceeded: Quota exceeded for query job",
        "S3 error: RequestTimeout: Your socket connection to the server was not read",
        "SQS error: InvalidParameterValue: Message must be shorter than 262144 bytes",
        "SNS error: KMSDisabledException: CMK is disabled, cannot publish message",
        "Lambda error: Runtime.ExitError: Process exited before completing request",
        "Lambda error: Task timed out after 30.00 seconds",
        "Lambda error: Runtime.ImportModuleError: Unable to import module handler",
        "ECS task stopped: Essential container exited with code 137 (OOM killed)",
        "EKS error: Evicted: The node was low on resource: memory",
        "Helm error: UPGRADE FAILED: another operation is in progress",
        "Terraform error: Error acquiring the state lock",
        "Docker error: No space left on device -- creating overlay2 layer",
        "pip error: Could not find a version that satisfies the requirement numpy>=1.26",
        "npm error: ERESOLVE unable to resolve dependency tree",
        "Maven build failed: Could not resolve dependencies for project",
        "Go build error: cannot find package database/sql in any of known paths",
        "Rust compilation error: mismatched types expected &str found String",
        "Ruby gem error: LoadError: cannot load such file -- openssl",
        "PHP error: Fatal error: Maximum execution time of 30 seconds exceeded",
        "PHP error: Fatal error: Allowed memory size of 134217728 bytes exhausted",
        "Python error: RecursionError: maximum recursion depth exceeded",
        "Python error: UnicodeDecodeError: invalid start byte at position 0",
        "Node.js error: Error: DEPTH_ZERO_SELF_SIGNED_CERT",
        "Node.js error: Error: certificate has expired",
        "Node.js error: RangeError: Maximum call stack size exceeded",
        "Java error: StackOverflowError at java.util.HashMap.getNode",
        "Java error: ClassNotFoundException: com.mysql.jdbc.Driver",
        "Java error: UnsatisfiedLinkError: no native-lib in java.library.path",
        "C# error: System.DivideByZeroException: Attempted to divide by zero",
        "C# error: System.InvalidOperationException: Sequence contains no elements",
        "Rust panic: called Option.unwrap() on a None value at src/main.rs:45",
        "Go panic: send on closed channel goroutine 42",
        "Error: Unsupported Media Type 415 for POST /api/v1/upload (expected multipart/form-data)",
        "Error: 422 Unprocessable Entity: email field must be a valid email address",
        "Error: 409 Conflict: resource orders/ORD-12345 was modified by another request",
        "Error: 410 Gone: resource users/deleted-user-123 has been permanently deleted",
        "Error: 413 Payload Too Large: request body 15.3MB exceeds limit 10MB",
        "Error: 414 URI Too Long: request-target exceeds 8192 bytes",
        "Error: 431 Request Header Fields Too Large: Cookie header 9.1KB exceeds limit",
        "Error: 503 Service Unavailable: maintenance mode active until 2024-01-15T14:00:00Z",
        "Error: 505 HTTP Version Not Supported: server requires HTTP/1.1 or HTTP/2",
        "AssertionError: expected 200 but got 500 for GET /api/v1/users/12345",
        "IntegrityError: null value in column user_id of relation orders violates not-null constraint",
        "OperationalError: could not connect to server: No such file or directory (socket /var/run/postgresql/.s.PGSQL.5432)",
        "ProgrammingError: column users.deleted_at does not exist",
        "DataError: invalid input syntax for type integer: NaN",
        "InternalError: deadlock detected",
        "NotSupportedError: nested transactions are not supported",
        "InterfaceError: connection already closed",
        "DatabaseError: server closed the connection unexpectedly",
        "OperationalError: SSL SYSCALL error: EOF detected",
        "cx_Oracle.DatabaseError: ORA-01000: maximum open cursors exceeded",
        "cx_Oracle.DatabaseError: ORA-00942: table or view does not exist",
        "pymongo.errors.ServerSelectionTimeoutError: localhost:27017: [WinError 10061]",
        "pymongo.errors.DuplicateKeyError: E11000 duplicate key error collection: prod.users",
        "redis.exceptions.ResponseError: WRONGTYPE Operation against a key holding wrong kind of value",
        "redis.exceptions.ConnectionError: Error 111 connecting to localhost:6379. Connection refused",
        "aiohttp.ServerDisconnectedError: Server disconnected",
        "aiohttp.ClientConnectorError: Cannot connect to host api.stripe.com:443",
        "requests.exceptions.SSLError: HTTPSConnectionPool(host=api.example.com, port=443): Max retries exceeded",
        "requests.exceptions.ConnectionError: HTTPConnectionPool(host=localhost, port=5432): Max retries exceeded",
        "requests.exceptions.Timeout: HTTPSConnectionPool read timed out after 30s",
        "boto3.exceptions.S3UploadFailedError: Failed to upload /tmp/file.pdf to prod-uploads/file.pdf",
        "botocore.exceptions.ClientError: An error occurred (NoSuchKey) on S3 GetObject",
        "google.api_core.exceptions.ResourceExhausted: 429 Quota exceeded for quota metric",
        "google.api_core.exceptions.NotFound: 404 Document not found: projects/prod/databases/(default)/documents/users/99999",
        "stripe.error.CardError: Your card was declined (decline_code: insufficient_funds)",
        "stripe.error.InvalidRequestError: No such customer: cus_invalid123",
        "stripe.error.RateLimitError: Too many requests made to the API too quickly",
        "twilio.base.exceptions.TwilioRestException: Unable to create record: Invalid to phone number",
        "sendgrid.exceptions.UnauthorizedError: The provided API key does not have the required scopes",
        "Error parsing YAML config at line 47: mapping values are not allowed here",
        "Error parsing JSON at position 1234: Unexpected token",
        "XML parse error at line 12: mismatched tag",
        "Schema validation error: additionalProperties is not allowed (got: user_name)",
        "Avro deserialization failed: Expected LONG, got STRING for field user_id",
        "Protobuf field 3 type mismatch: expected TYPE_STRING got TYPE_INT64",
        "HMAC signature mismatch: webhook payload may have been tampered",
        "CSRF token mismatch: expected abc123 got xyz789",
        "XSS attempt blocked: <script>alert(1)</script> in parameter username",
        "Path traversal attempt blocked: ../../etc/passwd in file parameter",
    ],
    "warning": [
        # Memory / CPU / disk pressure
        "High memory usage detected: 85% (6.8GB/8GB)",
        "High memory usage detected: 91% (7.3GB/8GB)",
        "idle connection to PostgreSQL server has been idle 3601s, closing",
        "idle connection to MySQL has been idle 7200s, closing",
        "heap memory usage at 78% of configured limit (3.9GB/5GB)",
        "heap memory usage at 82% of configured limit (4.1GB/5GB)",
        "CPU throttling detected: container cpu_limit=500m, actual_usage=480m (96%)",
        "Disk usage for /var/log is at 87%, consider rotating logs",
        "Disk usage for /data is at 92%, 8.3GB remaining",
        "Inode usage at 89% on /var/lib/docker, container creation may fail soon",
        # Slow queries / performance
        "slow query detected: 2847ms SELECT * FROM orders WHERE user_id=? (threshold: 500ms)",
        "slow query detected: 5123ms UPDATE sessions SET last_seen=NOW() (no index on last_seen)",
        "WARN [QueryExecutor] Query exceeded 1000ms: EXPLAIN shows sequential scan on table orders (rows=2.1M)",
        "N+1 query detected: 127 SELECT statements in single request to /api/users",
        "GC pause of 2.4s detected in JVM, may impact response latency",
        "GC pause of 4.1s detected in JVM, stop-the-world event",
        "Full GC triggered after 847 minor GCs: heap reclaimed 2.1GB",
        "Response time for GET /api/v1/products exceeded P99 threshold: 3200ms vs 1000ms SLA",
        # Replication / clustering
        "WARN [ReplicationManager] Replication lag is 45.2 seconds on replica postgres-2",
        "WARN [ReplicationManager] Replication lag is 128 seconds on replica postgres-3 (slot: replica_slot_1)",
        "slow consumer detected on topic=user-events, consumer_group=analytics, lag=150000",
        "slow consumer detected on topic=orders, consumer_group=reporting, lag=843221",
        "Redis replication: replica fell behind master by 32MB, resync required",
        "MongoDB secondary replication lag exceeded 30s: oplog window may be insufficient",
        "Cassandra: compaction fell behind writes; consider adding nodes or reducing write rate",
        # Certificate / security warnings
        "TLS 1.0 is deprecated, client 192.168.1.42 still negotiating old protocol",
        "TLS 1.1 deprecated connection from 10.0.0.5:52301",
        "SSL certificate for api.example.com expires in 14 days (expires: 2024-02-01)",
        "SSL certificate for internal.service.com expires in 7 days",
        "Weak cipher suite negotiated: RC4-MD5 from client 10.0.0.8",
        "Password hash algorithm SHA1 is deprecated, consider upgrading to bcrypt",
        "API key rotation overdue: key last_rotated=2023-01-15, policy requires 90 days",
        # Rate limiting / throttling
        "Rate limit approaching for service stripe-api: 95/100 req per second",
        "Rate limit approaching for service sendgrid: 580/600 emails per hour",
        "Throttling requests from IP 203.0.113.42: 450 requests in last 60 seconds",
        "API quota at 85%: 8500/10000 monthly API calls consumed",
        # Connection pools
        "Connection pool near capacity: 18/20 connections active (PostgreSQL)",
        "Connection pool near capacity: 47/50 connections active (Redis)",
        "Connection pool wait queue growing: 23 requests waiting for connection",
        "HTTP keep-alive connections: 892/1000 limit approaching",
        # Cache warnings
        "Cache miss ratio high: 67% for user profile cache (expected <20%)",
        "Cache eviction rate elevated: 1240 keys evicted per second (max_memory_policy: allkeys-lru)",
        "Cache hit ratio dropped below threshold: 45% (threshold: 80%)",
        "Redis memory fragmentation ratio: 1.87 (normal: <1.5)",
        # Deprecation / misconfiguration
        "Deprecated API endpoint /api/v1/users/list called by client iOS-App/3.2.1",
        "Deprecated config key 'max_pool_size' used; use 'pool.max_size' instead",
        "Deprecated: Using HTTP instead of HTTPS for internal service communication",
        "WARN: CORS wildcard (*) configured in production environment",
        "WARN: Running as root user, this is a security risk",
        "WARN: Debug logging enabled in production, may impact performance",
        # Retry / backoff warnings
        "Retry attempt 2/3 for HTTP POST to payment-gateway (ECONNRESET)",
        "Retry attempt 3/3 for database write after deadlock (order_id=ABC123)",
        "Exponential backoff: retry in 8192ms for failed job job_id=abc-123 (attempt 7/10)",
        "Circuit breaker HALF-OPEN: test request to inventory-service",
        "Message redelivery count exceeded 5 for message id=msg-xyz, moving to retry queue",
        # Resource warnings
        "Thread pool queue depth: 387 (warning threshold: 300)",
        "Event loop blocked for 280ms in Node.js worker (threshold: 100ms)",
        "Goroutine count: 12847 (warning threshold: 10000)",
        "File descriptor usage: 900/1024 (88%)",
        "Swap usage increased to 2.1GB (total: 4GB)",
        "Network bandwidth: 850Mbps of 1Gbps capacity",
        # Additional
        "Checkpointing taking longer than expected: 18s (threshold: 10s)",
        "Log rotation skipped: files locked by running process",
        "Health check latency spike: 2800ms for service inventory (normal: <200ms)",
        "WARN: job scheduler is 45 seconds behind schedule",
        "DNS TTL exceeded for cache entry api.external-service.com, using stale record",
        "Worker process memory growing continuously: 512MB->521MB->534MB in last 30 minutes",
        "Long-running transaction detected: BEGIN 3h42m ago, blocking 7 other queries",
        # Additional warning patterns
        "WARN: JWT token expiry in 300 seconds, consider refreshing",
        "WARN: API version v1 is deprecated, clients should migrate to v2 by 2024-06-01",
        "WARN: Unencrypted HTTP used for internal service call from api to payment",
        "WARN: Database password will expire in 7 days (policy: 90 days)",
        "WARN: Audit log destination unreachable, audit events buffered locally",
        "WARN: Request body parsing slower than expected: 1.2s for 2MB payload",
        "WARN: Too many open file descriptors: 900/1024, approaching system limit",
        "WARN: Signal handler registered for SIGTERM, graceful shutdown may not complete",
        "WARN: Dependency 'lodash@3.10.1' has known security vulnerability CVE-2021-23337",
        "WARN: npm audit found 3 moderate severity vulnerabilities",
        "WARN: Python package 'requests' version 2.28 has known vulnerability",
        "WARN: Running with --allow-root flag, security risk in production",
        "WARN: Insecure random number generator used for session token generation",
        "WARN: HTTP Strict Transport Security not enabled for api.example.com",
        "WARN: X-Frame-Options header missing on /admin route",
        "WARN: Content-Security-Policy not configured, XSS risk elevated",
        "WARN: Referrer-Policy not set, sensitive URLs may leak in referrer header",
        "WARN: CORS configuration allows credentials with wildcard origin",
        "WARN: Admin panel accessible without MFA requirement",
        "WARN: Unused index detected: idx_orders_status not used in 30 days",
        "WARN: Table 'audit_logs' has no primary key, performance may degrade",
        "WARN: 47 long-running queries (>5s) detected in last hour",
        "WARN: Autovacuum not keeping up with dead tuple accumulation in table orders",
        "WARN: Sequence 'users_id_seq' approaching maximum value (2.1B/2.1B)",
        "WARN: PostgreSQL checkpoint completion target exceeded: 90% complete in 45s",
        "WARN: Redis memory usage at 87% of maxmemory (4.35GB/5GB), eviction may occur",
        "WARN: Redis keyspace notification subscription lag: 1247 events behind",
        "WARN: Kafka consumer group lag increasing: +50000 messages in last 5 minutes",
        "WARN: Kafka producer batch size at 80% of max.request.size",
        "WARN: SQS queue depth growing: 15000 messages, DLQ at 80% threshold",
        "WARN: RabbitMQ queue 'orders.processing' has 5000 unacknowledged messages",
        "WARN: Elasticsearch cluster yellow: 23 unassigned replica shards",
        "WARN: MongoDB oplog window shrinking: estimated 6h until replication falls behind",
        "WARN: Cassandra compaction pending: 47 SSTables need compaction on node 3",
        "WARN: ClickHouse merge queue depth: 234 parts, performance may degrade",
        "WARN: S3 multipart upload not completed: 234 incomplete uploads older than 7 days",
        "WARN: CDN cache hit ratio dropped to 72% (baseline: 95%)",
        "WARN: Load balancer sticky session table 80% full: 40000/50000 sessions",
        "WARN: Health check response time degraded: 450ms (threshold: 200ms)",
        "WARN: Container image registry using self-signed certificate",
        "WARN: Pod resource requests not set for deployment api-server",
        "WARN: Kubernetes node worker-2 disk pressure detected",
        "WARN: Docker container running as root (UID 0) in production",
        "WARN: No liveness probe configured for container payment-service",
        "WARN: Horizontal pod autoscaler unable to scale: metrics server unavailable",
        "WARN: PersistentVolumeClaim 'postgres-data' storage 78% utilized",
        "WARN: Node taint toleration is too permissive (tolerates all taints)",
        "WARN: Service account has cluster-admin role, violates least privilege",
        "WARN: GitHub Actions secret may be exposed in build log line 234",
        "WARN: Terraform plan shows 15 resources will be destroyed",
        "WARN: Migration 0047 will lock table 'orders' with 8.2M rows for ~180s",
        "WARN: Feature flag rollout_payment_v2 at 100%, ready for permanent code removal",
        "WARN: Stale feature flag 'old_checkout_v1' still in codebase (enabled=false since 2023-01)",
        "WARN: A/B test variant B has significantly lower conversion (p=0.001)",
        "WARN: Email delivery rate dropped to 87%: 13% bounced in last hour",
        "WARN: SMS gateway response time: 4200ms (normal: <1000ms)",
        "WARN: Webhook delivery success rate: 78% (threshold: 95%)",
        "WARN: Payment gateway success rate dropped to 92% (normal: 99.5%)",
        "WARN: Third-party API latency increased 3x over last 15 minutes",
        "WARN: Canary deployment receiving 10x error rate vs stable track",
        "WARN: Distributed trace sampling rate dropped to 0.01% due to volume",
        "WARN: Log ingestion rate 3x normal: possible log storm in progress",
        "WARN: Metrics cardinality explosion detected: 50000 unique label combinations",
        "WARN: Prometheus TSDB compaction taking >5 minutes, disk I/O may be bottleneck",
        "WARN: Grafana dashboard data gap: missing 8 minutes of metrics",
        "WARN: Alert suppressed during maintenance window: firing=true suppressed=true",
        "WARN: On-call rotation has no backup coverage for next 48 hours",
        "WARN: Non-idempotent POST /api/v1/orders called 3 times with same payload",
        "WARN: Request validation bypassed via internal header X-Internal-Skip-Auth",
        "WARN: Large JSON payload: 8.9MB for GET /api/v1/products (consider pagination)",
        "WARN: Chatty client: IP 203.0.113.42 made 450 requests in 60s",
        "WARN: Retry storm detected: service worker sending 10x normal retry rate",
        "WARN: Backpressure signal ignored by producer: consumer queue at 95%",
        "WARN: Cache stampede detected for key=product_catalog (100 simultaneous misses)",
        "WARN: Dog-pile effect: 234 requests waiting on single slow database query",
        "WARN: Lock contention on table orders: avg wait=450ms (threshold: 100ms)",
        "WARN: N+1 query pattern detected in GET /api/v1/orders: 47 queries per request",
        "WARN: Unbounded query result: SELECT * FROM logs returned 500000 rows",
        "WARN: ORM lazy loading triggered 127 extra queries in single request",
        "WARN: Missing index: full table scan on users.email (2.1M rows)",
        "WARN: Hot row contention: users/12345 row locked by 15 concurrent transactions",
        "WARN: Partition pruning not applied: query scanning all 48 date partitions",
        "WARN: Connection not closed before returning to pool: possible connection leak",
        "WARN: Statement timeout applied and nearly reached: query took 4800ms (limit: 5000ms)",
        "WARN: Large transaction: 50000 rows modified in single transaction, log growth expected",
        "WARN: Temporary table not cleaned up: tmp_export_7823 still present after 2 hours",
        "WARN: Stack trace logged in production response: may expose internal details",
        "WARN: Detailed error message returned to client: SQL state included in 500 response",
        "WARN: Internal IP range 10.0.0.0/8 reachable from public endpoint",
        "WARN: Admin endpoint /actuator/env accessible without authentication",
        "WARN: Debug endpoint /debug/pprof accessible in production",
        "WARN: Timing oracle: login response time varies by 200ms between valid/invalid users",
        "WARN: Cookie missing Secure flag: session cookie sent over HTTP",
        "WARN: Cookie missing HttpOnly flag: session cookie accessible to JavaScript",
        "WARN: Cookie missing SameSite attribute: CSRF risk elevated",
        "WARN: Access token in URL query parameter: may leak in server logs and referrer",
        "WARN: Plaintext password logged in request body debug output at auth.py:89",
        "WARN: API key visible in error response: partial key abc12*** shown",
        "WARN: Verbose server header: Server: Apache/2.4.51 (Ubuntu) OpenSSL/1.1.1l",
        "WARN: Directory listing enabled on /static/ path",
        "WARN: Default credentials in use: admin/admin on internal Grafana instance",
        "WARN: Publicly readable S3 bucket: prod-user-avatars allows anonymous GetObject",
        "WARN: IAM role has AdministratorAccess policy attached (overly permissive)",
        "WARN: Cloud storage access log disabled for bucket prod-uploads",
        "WARN: CloudTrail logging disabled for region ap-southeast-1",
        "WARN: VPC Flow Logs not enabled for production VPC",
        "WARN: Security group allows 0.0.0.0/0 ingress on port 22 (SSH)",
        "WARN: RDS instance publicly accessible: prod-db.cluster.rds.amazonaws.com",
        "WARN: Lambda function has 15-minute timeout with no dead-letter queue configured",
        "WARN: SQS queue retention period at 87%: messages will expire in 8 hours",
        "WARN: Kinesis shard iterator expired: consumer fell too far behind",
        "WARN: SNS subscription not confirmed: endpoint may have been deleted",
        "WARN: API Gateway throttling limit hit: 503 returned to 12 clients",
        "WARN: CloudFront serving stale content: origin returned 503 3 times",
        "WARN: Spot instance interruption notice received: 2-minute warning",
        "WARN: Reserved instance coverage dropped to 72% (target: 90%)",
        "WARN: AWS account spending 87% of budget with 8 days remaining in month",
        "WARN: Container image using deprecated base: node:16-alpine (EOL 2024-04-30)",
        "WARN: Helm chart using deprecated API: extensions/v1beta1 removed in k8s 1.22",
        "WARN: Dependency pinned to git SHA instead of release tag: security risk",
        "WARN: .env file committed to repository in commit abc1234 (secret scanning alert)",
        "WARN: Hardcoded string password123 detected in config/database.yml",
        "WARN: Private key found in public GitHub repository: revocation recommended",
        "WARN: Slow startup: application took 47s to become healthy (threshold: 30s)",
        "WARN: JVM class loading taking 12s on startup (consider AOT compilation)",
        "WARN: Too many open websocket connections from IP 192.168.1.100: 500 connections",
        "WARN: Zombie goroutines detected: 234 goroutines blocked on channel receive >5m",
        "WARN: EventLoop utilization at 92% in last 5s (threshold: 85%)",
        "WARN: Worker pool queue depth: 847 tasks, workers=8 may be undersized",
        "WARN: Heap allocated object count growing: 1.2M -> 1.5M -> 1.8M per GC cycle",
        "WARN: Non-deterministic test detected: same test passed and failed in last 10 runs",
        "WARN: Slow disk I/O detected: write latency 450ms on /dev/sda (threshold: 100ms)",
    ],
    "info": [
        # HTTP access log style
        "GET /api/v1/users/123 200 42ms - Mozilla/5.0 Chrome/120.0.0.0",
        "POST /api/v1/orders 201 87ms - okhttp/4.9.0",
        "PUT /api/v1/users/456/profile 200 31ms - axios/1.4.0",
        "DELETE /api/v1/sessions/abc123 204 12ms - curl/7.88.0",
        "GET /health 200 3ms - kube-probe/1.28",
        "GET /metrics 200 8ms - prometheus/2.45",
        "POST /api/v2/auth/token 200 124ms - custom-client/1.0",
        "GET /api/v1/products?page=2&limit=50 200 68ms",
        "PATCH /api/v1/orders/ORD-12345 200 54ms",
        # Service lifecycle
        "Listening on 0.0.0.0:8080, pid=1, workers=4",
        "Listening on 0.0.0.0:3000, pid=1234, env=production",
        "Service api-gateway started successfully (version: 2.4.1, commit: a3f2b1c)",
        "Service worker-1 started successfully, registered to queue=email_notifications",
        "Graceful shutdown initiated, draining 23 in-flight requests",
        "Graceful shutdown complete, all 23 in-flight requests processed",
        "Server restart initiated: configuration change detected",
        "Rolling restart: 3/8 instances updated to version 2.5.0",
        # Configuration
        "Config reloaded from /etc/app/config.yaml (inotify event)",
        "Config reloaded: feature_flags.json updated (payment_v2=true, dark_mode=false)",
        "Environment variables validated successfully (45 required vars present)",
        "Feature flag payment_v2 enabled for 10% of users",
        "Feature flag dark_mode enabled for user group=beta_testers",
        # Database connections
        "Successfully connected to PostgreSQL replica set at postgres-primary:5432",
        "Successfully connected to MongoDB replica set rs0/mongo1:27017,mongo2:27017",
        "Redis cluster connected: 6 nodes healthy (3 primary, 3 replica)",
        "Elasticsearch cluster healthy: 5 nodes, 234 indices, 0 unassigned shards",
        "Database connection pool initialized: 10 connections established",
        # User events
        "User john.doe@example.com logged in from IP 203.0.113.42 (browser: Chrome 120)",
        "User jane.smith@example.com signed up via OAuth (provider: Google)",
        "User admin@example.com performed bulk export of 15234 records",
        "User account api_user_789 authenticated via API key (scope: read:orders)",
        "Password changed for user john.doe@example.com from 192.168.1.10",
        "Two-factor authentication enabled for user jane.smith@example.com",
        # Jobs / tasks
        "Cron job cleanup_sessions completed: 1247 expired sessions removed",
        "Cron job send_digest_emails completed: 8324 emails queued in 12.3s",
        "Batch job order_fulfillment_2024-01-15: 4521 orders processed, 0 errors",
        "Background job resize_images: processed 127/127 images in 34.2s",
        "Scheduled task database_vacuum started on table orders (estimated rows: 2.3M)",
        "Scheduled task database_vacuum completed: 423000 dead rows removed, duration=127s",
        "Message consumer started: topic=user-events, group=analytics, partitions=12",
        "Kafka consumer committed offsets: topic=orders, partition=3, offset=8234521",
        # Cache events
        "Cache warmed up successfully: 12473 keys loaded from Redis in 2.3s",
        "Cache invalidated for user_id=12345 (profile updated)",
        "Cache invalidated for product catalog: 15000 keys cleared",
        "CDN cache purged for path /api/v1/products/** (1247 files)",
        # Deployment / infra
        "Container image pulled: registry.example.com/api:2.4.1 (digest: sha256:abc123)",
        "Deployment api-service rolled out: 5/5 pods running (version: 2.4.1)",
        "Load balancer health check registered: api-server-3 added to pool",
        "TLS certificate renewed for api.example.com (valid until 2025-01-15)",
        "Auto-scaling triggered: adding 2 workers due to queue depth=450",
        "Auto-scaling triggered: removing 1 worker due to low utilization (CPU: 8%)",
        # Data operations
        "Data export completed: 45231 records exported to s3://backups/export-2024-01-15.csv",
        "Database backup completed: full backup 4.2GB to s3://db-backups/pg-2024-01-15.dump",
        "Index rebuild completed on table orders: duration=45s, index size=234MB",
        "Data migration 0045_add_user_preferences applied successfully (2.3M rows updated)",
        "Snapshot created for persistent volume claim postgres-data (size: 45GB)",
        # Additional
        "Rate limiter reset for IP 203.0.113.42 (window expired)",
        "JWT token refreshed for user session abc-123 (new expiry: +24h)",
        "Webhook delivered to https://example.com/hooks/orders (status: 200, attempt: 1)",
        "Email sent to jane.doe@example.com (message_id=<abc123@mail.example.com>)",
        "Metrics aggregation completed: 1M data points reduced to 1000 (interval: 1h)",
        "S3 multipart upload completed: file=reports/2024-01-15.pdf size=45.2MB parts=9",
        "DNS record updated: api.example.com A 203.0.113.42 TTL=300",
        "Audit log entry created: user=admin action=delete_user target=user_id=99999",
        # Additional info patterns
        "Application started in 2.347s (JVM running for 3.124s)",
        "Tomcat initialized with port(s): 8080 (http) 8443 (https)",
        "Root WebApplicationContext: initialization completed in 1234ms",
        "HikariPool-1 - Start completed in 1234ms, pool size: 10",
        "Flyway Community Edition 9.22.0 by Redgate",
        "Successfully validated 47 migrations (execution time 00:01.234s)",
        "Current version of schema public: 47",
        "Acquiring lock on table schema_version in PostgreSQL database",
        "Spring Security configured: CSRF protection enabled",
        "Actuator web endpoint health is enabled",
        "Registering beans for JMX exposure on startup",
        "Started DemoApplication in 3.456 seconds (process running for 4.123)",
        "Mapped GET /api/v1/users (produces: application/json)",
        "Mapped POST /api/v1/orders (consumes: application/json)",
        "Hibernate: create table users (id bigserial not null, email varchar(255))",
        "Quartz scheduler initialized: job store=RAMJobStore, threadPool=10",
        "Scheduled jobs: [SendDigestEmailsJob, CleanupExpiredTokensJob, GenerateReportsJob]",
        "Kafka listener container started: topics=[orders, user-events, payments]",
        "RabbitMQ listener initialized: queues=[email.notifications, sms.alerts]",
        "Redis connection pool initialized: host=redis.cluster:6379 maxIdle=8 maxActive=50",
        "S3 bucket configured: us-east-1/prod-uploads (server-side encryption: AES256)",
        "CloudFront distribution E1ABC123DEF456 configured for origin api.example.com",
        "Route53 health check passing for api.example.com (endpoint: /health)",
        "ALB target group healthy: 8/8 instances passing health checks",
        "Auto Scaling Group api-servers: 8 instances running (min=4, max=16, desired=8)",
        "RDS instance db-prod-1 status: available (Multi-AZ: enabled, backup: daily)",
        "ElastiCache cluster cache-prod-1 status: available (6 nodes, replication enabled)",
        "SES sending statistics: sent=15234 bounced=34 (0.22%) complaints=2 (0.01%)",
        "Lambda function api-authorizer cold start: 1234ms (warm invocation: 12ms)",
        "ECS task definition updated: api-service:47 (cpu=1024, memory=2048)",
        "CodeDeploy deployment d-ABC123: succeeded (1 instance updated, 0 failed)",
        "GitHub Actions workflow ci.yml: completed in 4m23s (build: pass, tests: pass)",
        "Docker build completed: app:2.4.1 (layers: 12, size: 234MB, cache: 78% hit)",
        "Helm release api-service upgraded to chart version 1.2.3 (app 2.4.1)",
        "Terraform apply complete: 3 added, 2 changed, 0 destroyed",
        "Ansible playbook completed: ok=45 changed=12 unreachable=0 failed=0",
        "Vault token renewed for service api-server (lease: 24h, renewable: true)",
        "Consul service registration updated: api-server health=passing tags=[prod,v2]",
        "Jaeger trace exported: service=api operation=POST_/orders duration=234ms",
        "OpenTelemetry exporter: batch exported 1000 spans in 12ms",
        "Prometheus metric scraped: api_requests_total{method=POST,status=201} = 12345",
        "Grafana alert Resolved: api_error_rate returned to normal (threshold: <1%)",
        "PagerDuty incident resolved: INC12345 (duration: 23m, MTTR: 23m)",
        "Slack notification sent: #alerts channel, incident resolved",
        "DataDog synthetic monitor api_health_check: passed (latency: 42ms)",
        "New Relic APM transaction: POST /api/v1/orders avg=87ms throughput=450rpm",
        "Sentry release 2.4.1 created with 15 new issues, 3 resolved",
        "Rollbar deploy tracked: environment=production version=2.4.1 user=ci-bot",
        "Feature flag rollout: new_checkout_v2 enabled for 25% of users",
        "A/B test started: checkout_button_color (control: blue, variant: green, 50/50)",
        "Segment event tracked: order_completed user_id=12345 revenue=99.99",
        "Mixpanel event sent: page_view property_count=15",
        "Amplitude event logged: session_start platform=iOS version=4.2.1",
        "Stripe webhook received: payment_intent.succeeded id=pi_abc123",
        "PayPal IPN verified: payment_status=Completed txn_id=3HM12345A678",
        "Braintree transaction settled: id=abc123 amount=99.99 currency=USD",
        "SendGrid email delivered: to=user@example.com message_id=<abc@sendgrid.net>",
        "Twilio SMS sent: to=+1234567890 status=delivered segments=1",
        "Mailchimp campaign sent: id=abc123 recipients=15234 open_rate=24.5%",
        "HubSpot contact synced: user_id=12345 properties_updated=5",
        "Salesforce lead created: id=00Q12345ABC owner=sales-team",
        "GDPR data export completed: user_id=12345 records=47 format=JSON",
        "GDPR deletion request processed: user_id=99999 tables_affected=12",
        "SOC2 audit log: privileged access by admin@example.com to prod database",
        "PCI compliance scan passed: 12 requirements verified, 0 failures",
        "SSL/TLS certificate renewed via Let's Encrypt for api.example.com",
        "ACME challenge completed: DNS-01 validation for *.example.com",
        "Dependabot PR merged: lodash 4.17.20 -> 4.17.21 (security patch)",
        "Snyk scan completed: 0 critical, 1 high, 3 medium vulnerabilities",
        "SonarQube analysis: quality gate PASSED (coverage=85%, duplication=2.1%)",
        "Load test completed: 10000 concurrent users, P95=234ms, P99=890ms, errors=0.01%",
        "Chaos experiment completed: latency injection 500ms, degradation detected and recovered",
        "Worker node worker-4 joined the cluster (total: 8 nodes, CPUs: 64, RAM: 256GB)",
        "Node worker-2 gracefully removed from load balancer pool (draining complete)",
        "Certificate rotation complete: new cert valid from 2024-01-15 to 2025-01-15",
        "Database vacuum completed: table=users dead_tuples=234521 removed in 45s",
        "Full-text search index rebuilt: 2.3M documents indexed in 4m23s",
        "Read replica promoted to primary: postgres-replica-2 -> postgres-primary",
        "Failover complete: primary database recovered, replica re-syncing",
        "Blue-green deploy complete: all traffic shifted from blue to green",
        "Canary deploy at 100%: promoting canary to stable (error rate: 0.02%)",
        "Shadow traffic replay complete: 0 discrepancies between v1 and v2 responses",
        "Rate limit quota reset for API consumer client_id=abc123 (monthly reset)",
        "Webhook retry successful: event order.completed delivered on attempt 3",
        "Dead letter queue processed: 234 messages replayed successfully",
        "Outbox pattern: 50000 events published from outbox table in 2m14s",
        "Event sourcing snapshot created: aggregate=Order id=12345 version=500",
        "CQRS projection rebuild complete: ReadModel=OrderSummary events=2.1M duration=4m",
        "Saga orchestrator: compensating transaction complete for saga-abc123",
        "API contract test passed: consumer=mobile-app provider=api-gateway 45 interactions",
        "Smoke test suite passed: 23/23 critical paths healthy after deploy",
        "Integration test suite passed: 456/456 tests in 4m23s",
        "E2E test suite passed: 89/89 scenarios in Cypress (browser: Chrome 120)",
        "Performance regression test passed: P99=890ms within 10% of baseline",
        "Security scan complete: 0 critical, 0 high, 2 medium (accepted risks)",
        "Dependency audit complete: 0 vulnerabilities found (245 packages checked)",
        "SAST scan complete: 0 critical findings, 3 informational",
        "DAST scan complete: 0 vulnerabilities found on https://api.example.com",
        "Penetration test finding closed: XSS in /search?q= patched and verified",
        "Bug bounty report validated: IDOR in /api/v1/users/{id} fixed in v2.4.2",
        "Incident review complete: INC-2024-001 root cause identified and action items logged",
        "Post-mortem published: database outage 2024-01-15 preventive measures implemented",
        "On-call handover complete: INC-2024-002 handed to APAC team with full context",
        "SLO report: error_rate 99.97% (target: 99.9%) latency_p99 234ms (target: 500ms)",
        "Cost optimization: reserved instance purchase saved $2300/month vs on-demand",
        "Capacity planning complete: recommend +2 worker nodes before Q2 traffic peak",
        "Architecture review approved: microservice extraction for payment-service",
        "API deprecation notice sent: v1 endpoints retiring in 90 days, 12 clients notified",
        "Data retention policy applied: 45231 records older than 2 years archived to S3",
        "GDPR right-to-erasure completed: user_id=99999 data removed from 8 systems",
        "PCI scan passed: quarterly external vulnerability scan zero findings",
        "SOC 2 Type II audit evidence collected: 47 control tests passed",
        "ISO 27001 nonconformity closed: NC-2024-003 corrective action verified",
        "Business continuity test passed: failover to DR site completed in 23 minutes",
        "Disaster recovery drill complete: RPO=5min RTO=23min (targets: RPO=15min RTO=60min)",
        "Backup restore tested successfully: 45GB database restored to staging in 12 minutes",
        "On-call alert resolved: no action required (auto-recovery detected)",
        "Scheduled maintenance complete: kernel patched on 8 nodes with zero downtime",
        "Blue-green DNS cutover: api.example.com -> 203.0.113.42 (TTL propagated in 312s)",
        "Cache pre-warming complete: 50000 keys loaded from persistent store in 8s",
        "A/B test concluded: variant B wins (conversion +4.3%, p=0.001), rolling out",
        "Feature flag cleanup: removed 12 stale flags from codebase (all disabled >90 days)",
        "Technical debt sprint: 23 TODOs resolved, test coverage +2.3% to 87.6%",
        "Automated remediation triggered: EBS volume expanded from 100GB to 150GB",
        "Self-healing activated: unhealthy pod restarted, health check passing in 15s",
        "Auto-remediation: stale connection closed and pool replenished (pool was at 0/10)",
        "Runbook automation: disk cleanup freed 23GB on /var/log (was at 95%)",
        "GitOps sync: cluster state reconciled with git HEAD abc1234 (0 drift detected)",
        "Rate limit headers set: X-RateLimit-Limit=500 X-RateLimit-Remaining=488 X-RateLimit-Reset=1705320060",
        "Service mesh circuit breaker closed: payment-service healthy for 60s",
        "Cross-region replication lag: us-east-1 -> eu-west-1 0.3s (threshold: 5s)",
        "Object storage lifecycle rule applied: 1247 objects transitioned to Glacier",
        "DNS-based load balancing: api.example.com -> [203.0.113.42, 203.0.113.43] (weighted 50/50)",
        "mTLS certificate rotated for service api-gateway (new cert CN=api-gateway valid 90d)",
        "gRPC health check: service=payment SERVING (checked 30s ago)",
        "Distributed rate limiter synced: 47 keys replicated across 3 nodes",
    ],
    "debug": [
        # SQL queries with timing
        "SELECT u.id, u.email, u.created_at FROM users u WHERE u.id = $1 -- 3.2ms rows=1",
        "SELECT o.id, o.status FROM orders o WHERE o.user_id = $1 AND o.status='pending' -- 12.4ms rows=23",
        "INSERT INTO events (type, payload, created_at) VALUES ($1, $2, NOW()) -- 2.1ms rows=1",
        "UPDATE sessions SET last_seen=$1, ip_address=$2 WHERE token=$3 -- 1.8ms rows=1",
        "DELETE FROM cache_entries WHERE expires_at < NOW() -- 45ms rows=1247",
        "SELECT COUNT(*) FROM orders WHERE created_at > NOW()-INTERVAL '1 day' -- 8.9ms rows=1",
        "BEGIN TRANSACTION isolation=READ_COMMITTED",
        "COMMIT (txid=5234821, duration=3.7ms, 3 statements)",
        "ROLLBACK (txid=5234822, reason=unique_violation, duration=1.2ms)",
        "EXPLAIN ANALYZE: seq scan on table sessions cost=0.00..4523.00 rows=234521",
        # Cache operations
        "cache HIT for key=user:session:abc123 ttl=287s",
        "cache HIT for key=product:catalog:page:2 ttl=3421s",
        "cache MISS for key=user:profile:99999 (not found)",
        "cache MISS for key=inventory:product:sku-ABC-123 (expired ttl=0)",
        "cache SET key=user:session:xyz789 ttl=3600s bytes=2048",
        "cache DEL key=user:session:abc123 (logout)",
        "cache INCR key=rate_limit:ip:203.0.113.42:minute new_value=47",
        "Redis LPUSH queue:email_notifications msg_id=abc123 queue_len=234",
        "Redis RPOP queue:background_jobs job_id=job-xyz789",
        "Memcached get hits=1247 misses=34 (97.3% hit rate) elapsed=0.3ms",
        # HTTP request/response details
        "Incoming request: POST /api/v1/orders headers={Content-Type: application/json, Content-Length: 342}",
        "Outgoing request: GET https://api.stripe.com/v1/charges/ch_abc123 timeout=5000ms",
        "Response: 200 OK Content-Type=application/json Content-Length=1247 X-Request-Id=req_xyz789",
        "Request middleware: auth_token validated for user_id=12345 scope=[read, write]",
        "Request middleware: rate_limit check passed for IP=203.0.113.42 count=12/500",
        "Route matched: GET /api/v1/users/:id -> UserController#show params={id: 12345}",
        # Worker / queue processing
        "Worker 3 picked up job_id=a4f3b2c1 from queue=email_notifications (wait=234ms)",
        "Worker 7 picked up job_id=b5e6d7f8 from queue=image_processing (wait=12ms)",
        "Job a4f3b2c1 completed successfully in 342ms (type=send_email to=user@example.com)",
        "Job b5e6d7f8 failed attempt 1/3, retrying in 5000ms (error=ECONNREFUSED smtp:25)",
        "Cron scheduler: next run of send_digest_emails in 3600s",
        "Message acknowledged: queue=orders msg_id=msg-abc123 consumer=order-processor-2",
        "Message nacked: queue=events msg_id=msg-xyz789 (processing failed, requeuing)",
        # Memory / buffer
        "Allocated 4096 byte buffer for request body, content-length=3891",
        "Allocated 65536 byte read buffer for socket fd=42",
        "Buffer pool: 234/512 buffers in use (45.7%)",
        "GC cycle 234: freed 45.2MB, pause=12ms, live_bytes=234MB",
        "Memory stats: heap_used=234MB heap_total=512MB external=12MB rss=456MB",
        # Threading / concurrency
        "Thread pool: 8/16 workers active, queue_depth=0",
        "Goroutine 1247 started: handler=/api/v1/products user_id=12345",
        "Goroutine 1247 completed in 42ms",
        "Acquired lock for resource=order-lock-12345 waited=0ms",
        "Released lock for resource=order-lock-12345 held=3ms",
        "Semaphore acquired: db_write_semaphore (permits=4/10 remaining)",
        # Network / socket
        "TCP connection established: local=0.0.0.0:8080 remote=203.0.113.42:54321 fd=47",
        "TCP connection closed: remote=203.0.113.42:54321 duration=342ms bytes_in=2341 bytes_out=1234",
        "WebSocket handshake completed for client ws://10.0.0.1:8080 socket_id=sock_abc123",
        "DNS resolution: api.stripe.com -> 104.16.0.0 (A record, ttl=300, elapsed=2.3ms)",
        "TLS handshake completed: cipher=TLS_AES_256_GCM_SHA384 version=TLSv1.3 elapsed=45ms",
        # Tracing / observability
        "Span started: trace_id=abc123def456 span_id=789xyz operation=db.query",
        "Span finished: trace_id=abc123def456 span_id=789xyz duration=12.3ms status=OK",
        "Sampling decision: trace_id=abc123def456 sampled=true rate=0.1",
        "Feature flag evaluated: flag=new_checkout_flow user_id=12345 result=true",
        # Config / startup
        "Loading config from /etc/app/config.yaml (env=production)",
        "Plugin loaded: payment-processor v2.1.4",
        "Dependency injection container initialized: 47 beans created",
        "Middleware chain registered: [cors, rateLimit, auth, validate, handler]",
        # Additional
        "Session deserialized: user_id=12345 expires_in=3421s",
        "JWT decoded: user_id=12345 scope=[read, write] exp=2024-01-15T12:00:00Z",
        "Pagination: page=2 per_page=50 offset=50 total=1247 total_pages=25",
        "File upload received: filename=report.pdf size=2.3MB mime=application/pdf",
        "Stream chunk received: id=stream-abc123 bytes=4096 total_received=65536",
        "Template rendered: layout=app view=users/show partials=3 duration=4.2ms",
        "Event published: type=order.created id=ORD-12345 routing_key=orders.created",
        "Scheduled retry: job_id=job-abc123 attempt=2/5 next_run=2024-01-15T12:05:00Z",
        # Additional debug patterns
        "DEBUG: entering function validateUserInput args={email: user@example.com, age: 25}",
        "DEBUG: exiting function validateUserInput return=true duration=0.2ms",
        "DEBUG: middleware cors executed origin=http://localhost:3000 allowed=true",
        "DEBUG: middleware auth executed user_id=12345 token_valid=true ttl=3421s",
        "DEBUG: middleware rateLimit executed ip=203.0.113.42 count=42/500 window=60s",
        "DEBUG: compiling template users/show.html.erb (cached=false)",
        "DEBUG: template cache hit users/index.html.erb (age=34s ttl=300s)",
        "DEBUG: connection checkout from pool took 0.3ms (pool_size=10/10 idle=1)",
        "DEBUG: connection checkin to pool duration=12.3ms total_used_time=12ms",
        "DEBUG: prepared statement cached: SELECT users WHERE id=? (hit 234 times)",
        "DEBUG: index scan on orders.user_id cost=0.43..8.45 actual_rows=23 loops=1",
        "DEBUG: sequential scan avoided by index idx_orders_created_at",
        "DEBUG: query plan: hash join (cost=234.5 rows=1234 width=128)",
        "DEBUG: autovacuum: table orders: index scans: 0 pages: removed 1234 remain 45234",
        "DEBUG: lock acquired: ShareLock on relation 16384 in 0.1ms",
        "DEBUG: lock released: ShareLock on relation 16384 held=3.2ms",
        "DEBUG: checkpoint starting: time 2024-01-15 12:00:00 UTC",
        "DEBUG: checkpoint complete: wrote 234 buffers (1.4%) in 12.3s",
        "DEBUG: WAL segment archived: 00000001000000010000007A -> s3://backups/wal/",
        "DEBUG: replication slot consumed: slot=replica1 lsn=0/7B000000 lag=0B",
        "DEBUG: HTTP keep-alive connection reused: remote=203.0.113.42 requests=5",
        "DEBUG: HTTP connection upgraded to WebSocket: fd=47 origin=localhost",
        "DEBUG: HTTP/2 stream opened: stream_id=1 method=GET path=/api/v1/users",
        "DEBUG: HTTP/2 GOAWAY frame sent: last_stream_id=47 error=NO_ERROR",
        "DEBUG: gzip compression: original=45231B compressed=8921B ratio=80.3%",
        "DEBUG: content negotiation: client accepts [application/json, text/html] -> application/json",
        "DEBUG: etag validation: If-None-Match=abc123 matches current etag, 304 response",
        "DEBUG: cache-control: max-age=3600 s-maxage=86400 stale-while-revalidate=60",
        "DEBUG: request validation passed: schema=CreateOrderRequest fields=7 duration=0.8ms",
        "DEBUG: request deserialized: OrderRequest{userId=12345, items=3, total=99.99} in 0.5ms",
        "DEBUG: response serialized: OrderResponse{id=ORD-12345, status=pending} in 0.3ms",
        "DEBUG: encryption: AES-256-GCM encrypt 1024B -> 1056B key_id=key-abc123",
        "DEBUG: decryption: AES-256-GCM decrypt 1056B -> 1024B key_id=key-abc123",
        "DEBUG: hashing: bcrypt cost=12 input=password time=234ms",
        "DEBUG: JWT signed: alg=RS256 kid=key-2024-01 exp=+3600s",
        "DEBUG: JWT verified: claims={sub: 12345, scope: read write} valid=true",
        "DEBUG: OAuth2 token introspection: active=true scope=read write exp=1705320000",
        "DEBUG: SAML assertion validated: issuer=idp.example.com subject=john@corp.com",
        "DEBUG: LDAP bind successful: cn=api-service,dc=corp,dc=com",
        "DEBUG: LDAP search: base=ou=users filter=(uid=john) results=1 duration=12ms",
        "DEBUG: feature flag 'new_payment_ui' evaluated: user_id=12345 segment=beta result=true",
        "DEBUG: experiment 'checkout_v2' assigned: user_id=12345 variant=control",
        "DEBUG: analytics event queued: order_completed user=12345 properties=8",
        "DEBUG: outbox event persisted: type=OrderCreated aggregate=12345 position=8234",
        "DEBUG: saga step completed: SagaId=saga-abc123 step=ReserveInventory state=COMPENSATING",
        "DEBUG: circuit breaker state: service=payment status=CLOSED failures=0 threshold=5",
        "DEBUG: retry policy: attempt=2 delay=2000ms jitter=234ms next_delay=4000ms",
        "DEBUG: rate limiter token bucket: tokens=42.3 rate=100/s burst=500",
        "DEBUG: distributed lock acquired: resource=order-lock-12345 node=worker-1 ttl=30s",
        "DEBUG: distributed lock heartbeat: resource=order-lock-12345 renewed=true",
        "DEBUG: leader election: node=worker-1 became leader term=47",
        "DEBUG: gossip protocol: received cluster state update from node worker-3",
        "DEBUG: consistent hash: key=user:12345 -> node=cache-server-2 (slot=7823)",
        "DEBUG: read replica selected: replica=postgres-replica-2 (lag=12ms < threshold=100ms)",
        "DEBUG: read-your-writes: forcing primary read for user=12345 (wrote 45ms ago)",
        "DEBUG: connection pool: waiting 1.2ms for available connection (pool_size=10/10)",
        "DEBUG: slow path: cache miss for user:12345:orders, falling back to database",
        "DEBUG: materialized view refresh: orders_summary duration=234ms rows_updated=45231",
        "DEBUG: batch insert: 100 rows into events table in 12ms (10000 rows/sec)",
        "DEBUG: cursor-based pagination: after_id=12345 limit=50 results=50 has_more=true",
        "DEBUG: full-text search: query=database connection terms=2 results=47 duration=23ms",
        "DEBUG: geo query: WITHIN CIRCLE lat=37.7749 lon=-122.4194 radius=10km results=234",
        "DEBUG: time-series query: metric=cpu_usage start=-1h step=60s points=60 duration=8ms",
        "DEBUG: aggregation pipeline: $group $sort $limit processed 45231 docs in 234ms",
        "DEBUG: background worker exited cleanly: worker_id=3 jobs_processed=234 uptime=3600s",
        "DEBUG: process signal received: SIGUSR1, reloading configuration",
        "DEBUG: profiling sample: function=getUser CPU=2.3% MEM=0.1% calls=1247",
        "DEBUG: heap snapshot triggered: size=234MB objects=1234567 duration=1234ms",
        "DEBUG: async task scheduled: name=cleanup_sessions delay=3600s",
        "DEBUG: event loop lag: 12ms (threshold: 100ms) loop_iteration=234567",
        "DEBUG: connection state machine: ESTABLISHED -> CLOSE_WAIT -> CLOSED fd=47",
        "DEBUG: TLS session resumed: session_id=abc123 cipher=TLS_AES_256_GCM_SHA384",
        "DEBUG: compression: lz4 compress 45231B -> 8921B ratio=80.3% duration=0.3ms",
        "DEBUG: serialization format: protobuf message OrderEvent size=234B fields=12",
        "DEBUG: schema registry: fetching schema id=47 version=3 for topic=orders",
        "DEBUG: dead letter queue: message msg-abc123 moved after 3 failed attempts",
        "DEBUG: idempotency key=idem-abc123 found in store, returning cached response",
        "DEBUG: request id=req-abc123 correlated across 4 services in trace",
        "DEBUG: baggage propagated: tenant_id=tenant-1 request_id=req-abc123",
        "DEBUG: span attribute added: db.statement=SELECT users WHERE id=12345",
        "DEBUG: metric recorded: http_request_duration_seconds{method=POST} observation=0.087",
        "DEBUG: log level dynamically changed: root=INFO com.app.service=DEBUG",
        "DEBUG: config value read: database.pool.max=10 source=env override=false",
        "DEBUG: config reload: 3 values changed, 0 values removed, 47 values unchanged",
        "DEBUG: dependency graph: api -> [database, cache, auth] resolved in 2ms",
        "DEBUG: service discovery: resolved payment-service to 10.0.0.7:8080 via consul",
        "DEBUG: sidecar proxy intercepted request: src=api dst=payment latency=0.3ms",
        "DEBUG: mTLS handshake: client cert CN=api-service O=example.com verified",
        "DEBUG: authorization policy: allow GET /api/v1/users (principal=api-service roles=[reader])",
        "DEBUG: OPA policy evaluated: input={method:GET path:/api/v1/orders} result=allow",
        "DEBUG: request coalescing: 5 identical requests merged into 1 upstream call",
        "DEBUG: response cached: GET /api/v1/products ttl=300s vary=Accept-Language",
        "DEBUG: stale-while-revalidate: serving cached response while refreshing in background",
        "DEBUG: cache warm: prefetching user:12345:orders in background",
        "DEBUG: object pool: acquired pooled object type=HttpClient id=pool-7 (pool_size=8)",
        "DEBUG: object pool: returned HttpClient id=pool-7 (pool_size=8 idle=7)",
        "DEBUG: connection multiplexing: 8 requests multiplexed over 2 HTTP/2 connections",
        "DEBUG: WebSocket message received: type=ping from=client-abc123 size=2B",
        "DEBUG: WebSocket message sent: type=pong to=client-abc123 size=2B",
        "DEBUG: SSE event sent: event=log-update data_size=512B clients=23",
        "DEBUG: long-poll request completed: client waited 28.3s for data",
        "DEBUG: backpressure: producer slowed from 1000/s to 100/s (consumer lag=50000)",
        "DEBUG: flow control: HTTP/2 WINDOW_UPDATE stream=1 increment=65535",
        "DEBUG: chunked transfer: sent 5 chunks total=45231B to client abc123",
        "DEBUG: multipart response: boundary=----Boundary1234 parts=3",
        "DEBUG: content negotiation: gzip accepted by client, compressing response",
        "DEBUG: proxy pass: -> http://upstream-1:8080/api/v1/users duration=12ms status=200",
        "DEBUG: upstream selected: round-robin chose server 3 (upstream-3:8080)",
        "DEBUG: upstream health: upstream-2:8080 passing (2/3 checks ok)",
        "DEBUG: sticky session: routing to upstream-1 (session=sess_abc123)",
        "DEBUG: A/B routing: 50% traffic to variant=B based on cookie ab_test=variant_b",
        "DEBUG: feature toggle: user 12345 in segment beta -> feature=new_ui enabled",
        "DEBUG: rollout: 10% of users (hash=45) receive new_checkout_v2=true",
        "DEBUG: shadow mode: request mirrored to shadow service v2 (response discarded)",
        "DEBUG: canary check: canary error rate 0.02% < threshold 1% -> continue rollout",
        "DEBUG: graceful shutdown: waiting for 23 in-flight requests to complete",
        "DEBUG: signal received SIGTERM: starting graceful shutdown sequence",
        "DEBUG: deregistering from service registry: api-server-3 marked unavailable",
        "DEBUG: closing idle connections: 5 keep-alive connections closed on shutdown",
        "DEBUG: flush metrics: 50000 buffered data points flushed to prometheus",
        "DEBUG: trace sampling: user_id=12345 sampled=true (rate=0.1 forced=false)",
        "DEBUG: baggage item added: tenant_id=tenant-123 to current trace context",
        "DEBUG: correlation id: X-Request-Id=req-abc123def456 propagated to downstream",
        "DEBUG: structured log: {level:debug, component:cache, operation:get, key:user:12345, hit:false}",
        "DEBUG: log enrichment: added fields pod=api-server-2 namespace=production node=worker-1",
        "DEBUG: dynamic sampling: high-error user_id=12345 sampled at rate=1.0",
        "DEBUG: resource usage snapshot: goroutines=234 fds=47 heap=456MB",
        "DEBUG: ticker fired: cleanup_expired_sessions interval=3600s",
        "DEBUG: cron expression evaluated: 0 */6 * * * -> next_run=2024-01-15T18:00:00Z",
        "DEBUG: job queue depth: pending=12 running=4 completed=234 failed=0",
        "DEBUG: worker heartbeat: worker-3 alive jobs_processed=234 queue=email",
        "DEBUG: priority queue: job job-abc123 priority=HIGH inserted at position 1",
        "DEBUG: deduplication check: message msg-abc123 already processed (idempotency)",
        "DEBUG: message visibility timeout extended: msg-abc123 new_timeout=+300s",
        "DEBUG: partition assignment: consumer=consumer-1 partitions=[0,1,2] topic=orders",
        "DEBUG: offset commit: topic=orders partition=0 offset=8234521 group=analytics",
        "DEBUG: consumer lag: topic=orders partition=0 lag=0 (caught up)",
        "DEBUG: producer record sent: topic=events partition=3 offset=1234567 key=user:12345",
    ]
}

# Augmentation helpers — apply realistic numeric variation to patterns that
# describe quantities, making repeated draws of the same base pattern produce
# distinct samples.
_NUMERIC_AUGMENTORS = {
    "critical": [
        lambda p: p.replace("12453", str(random.randint(1000, 99999))),
        lambda p: p.replace("7823", str(random.randint(1000, 99999))),
    ],
    "error": [
        lambda p: p.replace("5432", str(random.choice([5432, 5433, 5434, 3306, 27017, 9200]))),
        lambda p: p.replace("123", str(random.randint(100, 999))),
    ],
    "warning": [
        lambda p: p.replace("85%", f"{random.randint(75, 95)}%"),
        lambda p: p.replace("2847ms", f"{random.randint(500, 9000)}ms"),
        lambda p: p.replace("45.2", f"{random.uniform(10, 180):.1f}"),
    ],
    "info": [
        lambda p: p.replace("42ms", f"{random.randint(5, 500)}ms"),
        lambda p: p.replace("123", str(random.randint(100, 999999))),
        lambda p: p.replace("1247", str(random.randint(100, 99999))),
    ],
    "debug": [
        lambda p: p.replace("3.2ms", f"{random.uniform(0.1, 50):.1f}ms"),
        lambda p: p.replace("abc123", f"{''.join(random.choices('abcdef0123456789', k=8))}"),
        lambda p: p.replace("12345", str(random.randint(1000, 99999))),
    ],
}


class LogDataGenerator:
    """Generate synthetic log data for training the classifier."""

    def __init__(self):
        # Template-based patterns (fill-in-the-blank style)
        self.log_templates = {
            "critical": [
                "System crash detected in module {module}",
                "Fatal error: Out of memory in {module}",
                "Database connection failed permanently",
                "Security breach detected from IP {ip}",
                "Critical service {service} is down",
                "Data corruption detected in {module}",
                "System kernel panic in {module}",
                "Fatal authentication failure",
                "Critical resource exhaustion in {service}",
                "Unrecoverable error in {module}",
                "Complete service failure: {service} is unreachable",
                "Fatal disk write failure in {module}",
                "System entering emergency shutdown",
                "Catastrophic failure in {service}: all connections dropped",
            ],
            "error": [
                "Failed to connect to {service}",
                "Error processing request in {module}",
                "Exception in {module}: {error_type}",
                "Database query failed: {error_type}",
                "API call failed: {error_type}",
                "File not found: {file}",
                "Permission denied in {module}",
                "Timeout error in {service}",
                "Invalid response from {service}",
                "Failed to parse data in {module}",
                "Authentication error in {module}: invalid credentials",
                "Unexpected error in {module}: {error_type}",
                "Write operation failed in {service}",
                "Read operation failed in {module}",
            ],
            "warning": [
                "High memory usage detected: {percent}%",
                "Slow query detected in {module}",
                "Deprecated API usage in {module}",
                "Rate limit approaching for {service}",
                "Cache miss ratio high in {module}",
                "Retry attempt {num} for {service}",
                "Connection pool near capacity",
                "Disk space running low: {percent}%",
                "SSL certificate expires soon",
                "Performance degradation in {module}",
                "CPU usage elevated: {percent}% in {service}",
                "Queue depth growing in {service}",
                "Replication lag detected in {module}",
            ],
            "info": [
                "Request processed successfully in {module}",
                "User logged in: {user}",
                "Service {service} started successfully",
                "Configuration reloaded",
                "Cache refreshed for {module}",
                "Scheduled task completed: {task}",
                "Connection established to {service}",
                "Data backup completed successfully",
                "New session created for user {user}",
                "Health check passed for {service}",
                "Deployment completed for {service}",
                "User {user} logged out",
                "Data sync completed for {module}",
            ],
            "debug": [
                "Processing request ID: {id}",
                "Function {function} called with params {params}",
                "Variable state: {variable}={value}",
                "Entering method {method} in {module}",
                "Loop iteration {num} in {module}",
                "Query execution time: {time}ms",
                "Response size: {size} bytes",
                "Cache hit for key: {key}",
                "Thread {thread} started",
                "Debug checkpoint reached in {module}",
                "Request routed to handler in {module}",
                "Serialization completed in {time}ms",
            ],
        }

        self.modules  = ["auth", "api", "database", "cache", "payment", "user-service", "order-service", "notification"]
        self.services = ["Redis", "PostgreSQL", "MongoDB", "Elasticsearch", "RabbitMQ", "Nginx", "Kafka", "MySQL"]
        self.error_types = ["NullPointerException", "TimeoutException", "ConnectionError", "ValueError", "TypeError",
                            "DeadlockException", "SocketException", "IOException"]
        self.users  = ["john_doe", "jane_smith", "admin", "test_user", "api_client", "service_account"]

    # ── Real-world sample generation ──────────────────────────────────────────

    def generate_real_world_sample(self, severity: str) -> dict:
        """Pick a real-world pattern, apply light numeric variation, return a log dict."""
        patterns   = REAL_WORLD_PATTERNS[severity]
        pattern    = random.choice(patterns)
        augmentors = _NUMERIC_AUGMENTORS.get(severity, [])
        if augmentors and random.random() < 0.4:
            try:
                pattern = random.choice(augmentors)(pattern)
            except Exception:
                pass
        return {
            "message":   pattern,
            "severity":  severity,
            "source":    random.choice(self.modules),
            "timestamp": datetime.now().isoformat()
        }

    # ── Template-based sample generation ─────────────────────────────────────

    def generate_template_log(self, severity=None) -> dict:
        if severity is None:
            severity = random.choice(list(self.log_templates.keys()))

        template = random.choice(self.log_templates[severity])
        message  = template.format(
            module     = random.choice(self.modules),
            service    = random.choice(self.services),
            error_type = random.choice(self.error_types),
            ip         = f"{random.randint(1,255)}.{random.randint(1,255)}.{random.randint(1,255)}.{random.randint(1,255)}",
            file       = f"/var/log/{random.choice(self.modules)}.log",
            percent    = random.randint(60, 95),
            num        = random.randint(1, 5),
            user       = random.choice(self.users),
            task       = f"task_{random.randint(1000, 9999)}",
            id         = f"req_{random.randint(10000, 99999)}",
            function   = f"process_{random.choice(['data', 'request', 'response', 'payload'])}",
            params     = f"{{id: {random.randint(1, 100)}}}",
            variable   = random.choice(['user_id', 'order_id', 'session_id', 'product_id']),
            value      = random.randint(1, 1000),
            method     = random.choice(['authenticate', 'validate', 'process', 'execute', 'query']),
            time       = random.randint(10, 500),
            size       = random.randint(100, 10000),
            key        = f"cache_key_{random.randint(1, 100)}",
            thread     = f"thread_{random.randint(1, 10)}"
        )
        return {
            "message":   message,
            "severity":  severity,
            "source":    random.choice(self.modules),
            "timestamp": datetime.now().isoformat()
        }

    # ── Dataset generation ────────────────────────────────────────────────────

    def generate_dataset(self, size: int = 6000) -> pd.DataFrame:
        """
        Generate a balanced training dataset.

        Each class receives:
          - 200 samples from REAL_WORLD_PATTERNS  (diverse, realistic)
          - remainder from template-based generation

        Total dataset = 5 × (200 real + N template) logs, shuffled.
        """
        severity_levels  = list(self.log_templates.keys())
        real_per_class   = 200
        template_per_class = max(0, (size // len(severity_levels)) - real_per_class)

        logs = []
        for severity in severity_levels:
            # Real-world samples
            for _ in range(real_per_class):
                logs.append(self.generate_real_world_sample(severity))
            # Template samples
            for _ in range(template_per_class):
                logs.append(self.generate_template_log(severity))

        # Top-up to exact size with random template logs
        while len(logs) < size:
            logs.append(self.generate_template_log())

        random.shuffle(logs)
        df = pd.DataFrame(logs)
        print(f"[OK] Generated {len(df)} training samples")
        print(f"     Real-world : {real_per_class * len(severity_levels)} ({real_per_class} x {len(severity_levels)} classes)")
        print(f"     Template   : {len(df) - real_per_class * len(severity_levels)}")
        print(f"[Stats] Distribution:\n{df['severity'].value_counts()}")
        return df


if __name__ == "__main__":
    generator = LogDataGenerator()
    df = generator.generate_dataset(6000)
    print("\nSample logs (first 10):")
    print(df.head(10).to_string())
